const lyrics = [
    { time: 0, text: "Are you ready, hey, are you ready for this?", singer:"freddie" },
    { time: 2, text: "Are you hanging on the edge of your seat?", singer:"freddie"},
    { time: 3, text: "I need a break beat, uh", singer:"other"},
    { time: 4, text: "Are you ready, hey, are you ready for this?", singer:"freddie"},
    { time: 7, text: "Are you hanging on the edge of your seat?", singer:"freddie"},
    { time: 8, text: "I need a break beat, uh", singer:"other"},
    { time: 9, text: "Are you ready, hey, are you ready for this?", singer:"freddie"},
    { time: 11, text: "Are you hanging on the edge of your seat?", singer:"freddie"},
    { time: 13, text: "I need a break beat, uh", singer:"other"},
    { time: 14, text: "Outta the doorway the bullets rip", singer:"freddie"},
    { time: 16, text: "Repeating to the sound of the beat, hey", singer:"freddie"},

    { time: 17, text: "Yo, a for the kids in the club that's ready to get bugged", singer:"other"},
    { time: 20, text: "Another one bites the dust", singer:"freddie"},
    { time: 22, text: "And for the thugs with the burners that wanna blast off", singer:"other"},
    { time: 25, text: "Another ones bites the dust", singer:"freddie"},
    { time: 27, text: "And for the kids on the blocks, shootin' at the crooked cops-blaow!", singer:"other"},
    { time: 29, text: "Another one bites the dust", singer:"freddie"},
    { time: 31, text: "And another one gone", singer:"freddie"},
    { time: 32, text: "Wyclef", singer:"other"},
    { time: 33, text: "And another one gone", singer:"freddie"},
    { time: 33, text: "Dirty Cash", singer:"other"},
    { time: 34, text: "Another one bites the dust", singer:"freddie"},
    { time: 34, text: "Young Free", singer:"other"},
    { time: 36, text: "Freddie where you at?", singer:"other"},

    { time: 37, text: "Steve walks wearily down the street", singer:"freddie"},
    { time: 38, text: "With the brim pulled way down low", singer:"freddie"},
    { time: 41, text: "Some cat up in Brooklyn just got robbed with a Kangol", singer:"other"},
    { time: 45, text: "Are you ready, hey, are you ready for this?", singer:"freddie"},
    { time: 47, text: "Are you hanging on the edge of your seat?", singer:"freddie"},
    { time: 50, text: "Out of the doorway, the bullets rip", singer:"freddie"},
    { time: 52, text: "Repeating to the sound of the beat, hey", singer:"freddie"},
    { time: 54, text: "My man got shot, and the block got hot", singer:"other"},
    { time: 56, text: "Another one bites the dust", singer:"freddie"},
    { time: 58, text: "Yo, hey I hear more shots, this is like Fort Knox, kid", singer:"other"},
    { time: 61, text: "Another one bites the dust", singer:"freddie"},
    { time: 62, text: "Yo, hold your breath", singer:"other"},
    { time: 63, text: "And another one gone", singer:"freddie"},
    { time: 64, text: "Hold your breath", singer:"other"},
    { time: 64, text: "And another one gone", singer:"freddie"},
    { time: 65, text: "Hold your breath", singer:"other"},
    { time: 65, text: "Another one bites the dust", singer:"freddie"},
    { time: 66, text: "Yo, check it", singer:"other"},

    { time: 68, text: "If you're a soldier at ease", singer:"other"},
    { time: 69, text: "My military style is known to murder Nazis", singer:"other"},
    { time: 71, text: "Brooklyn to Germany", singer:"other"},
    { time: 72, text: "Oh yeah", singer:"freddie"},
    { time: 72.5, text: "Come on", singer:"other"},
    { time: 73.5, text: "My kamikaze will blow the U2", singer:"other"},
    { time: 75, text: "They hire Idi Amin in Timbuktu", singer:"other"},
    { time: 77, text: "Whether you Hindu, or do the Voodoo", singer:"other"},
    { time: 79, text: "You can't foresee this unless I bring the", singer:"other"},
    { time: 81, text: "previews, yeah, yeah", singer:"other"},
    { time: 84, text: "Yo, it's the number one rappin' band", singer:"other"},
    { time: 85.5, text: "Come on", singer:"freddie"},
    { time: 86.5, text: "Yo, this review will be critically acclaimed", singer:"other"},
    { time: 88.5, text: "Leave you in critical pain, clinically insane", singer:"other"},
    { time: 90.5, text: "The name Wyclef Jean, with a yes, yes y'all", singer:"other"},
    { time: 93, text: "Better have a vest y'all, I'll blast, and bless y'all", singer:"other"},
    { time: 94, text: "Oh yeah", singer:"freddie"},
    { time: 95, text: "F-y'all, the mark of the beast, the triple six", singer:"other"},
    { time: 97.5, text: "Time running out, listen to the tick", singer:"other"},
    { time: 99, text: "Oh yeah", singer:"freddie"},
    { time: 100, text: "If you see what I saw, then you seen what I seen", singer:"other"},
    { time: 102, text: "If you know what I know, you know what I mean", singer:"other"},
    { time: 103.5, text: "Oh yeah", singer:"freddie"},
    { time: 104.5, text: "Commanding officer of the Navy SEAL team", singer:"other"},
    { time: 106.5, text: "Once I give the orders, you feel the infrared beam", singer:"other"},
    { time: 108, text: "Oh yeah", singer:"freddie"},
    { time: 109, text: "Blaow!", singer:"other"},
    { time: 109, text: "For all you critics, sayin' \"another remake\"", singer:"other"},
    { time: 111, text: "Another one bites the dust", singer:"freddie"},
    { time: 112.5, text: "Yo, if you know the deal, this is the master reel, kid", singer:"other"},
    { time: 115.5, text: "Another one bites the dust", singer:"freddie"},
    { time: 117, text: "Oh yeah", singer:"freddie"},
    { time: 118, text: "And another one gone", singer:"freddie"},
    { time: 118.5, text: "Right", singer:"other"},
    { time: 119.5, text: "And another one gone", singer:"freddie"},
    { time: 120, text: "Right", singer:"other"},
    { time: 121, text: "Another one bites the dust, hey", singer:"freddie"},
    { time: 121, text: "Freddie Mercury, where you at yo?", singer:"other"},

    { time: 122.5, text: "How do you think I'm gonna get along", singer:"freddie"},
    { time: 124.5, text: "Without you when you're gone", singer:"freddie"},
    { time: 126, text: "Oh yeah", singer:"freddie"},
    { time: 126, text: "I need a break yo", singer:"other"},
    { time: 126.5, text: "If you're ready for the first of the month", singer:"other"},
    { time: 128.5, text: "For that welfare check, come on", singer:"other"},
    { time: 129, text: "Kicked me out on my own", singer:"freddie"},
    { time: 130, text: "I need a break beat", singer:"other"},
    { time: 131.5, text: "Are you happy, are you satisfied?", singer:"freddie"},
    { time: 133.5, text: "How long can you stand the heat?", singer:"freddie"},
    { time: 135, text: "I need a break beat", singer:"other"},
    { time: 136, text: "Outta the doorway, the bullets rip", singer:"freddie"},
    { time: 138.5, text: "To the sound of the beat, look out", singer:"freddie"},
    { time: 139.5, text: "Yo, bulletproof vests, like the wild, wild west", singer:"other"},
    { time: 143, text: "Another one bites the dust", singer:"freddie"},
    {time: 144, text: "Yo, this is a stickup, now take off your rolex", singer:"other"},
    {time: 147.5, text: "Another one bites the dust", singer: "freddie"},
    { time: 150, text: "Yo, dirty money, good money, yo it's all money-money", singer:"other"},
    { time: 152, text: "Another one bites the dust", singer:"freddie"},
    { time: 153.5, text: "Yo, Dirty Cash", singer:"other"},
    { time: 153.5, text: "And another one gone", singer:"freddie"},
    { time: 154.5, text: "Dirty Cash", singer:"other"},
    { time: 154.5, text: "And another one gone", singer:"freddie"},
    { time: 156.5, text: "The adventures of Dirty Cash", singer:"other"},
    { time: 156.5, text: "Another one bites the dust", singer:"freddie"},

    { time: 157.5, text: "Yo, for the love for the cash, I'll blast you in my path", singer:"other"},
    { time: 160.5, text: "Keep my eyes on the math, you cats don't know the half", singer:"other"},
    { time: 162, text: "Oh yeah", singer:"freddie"},
    { time: 163.5, text: "As far as I'm concerned, you cats can burn in flames", singer:"other"},
    { time: 165.5, text: "This ain't no game, I'mma start callin' names", singer:"other"},
    { time: 167, text: "Oh yeah", singer:"freddie"},
    { time: 167.5, text: "So come get me, if you know the one-fifty", singer:"other"},
    { time: 170, text: "A million refugees ready to bust with me", singer:"other"},
    { time: 171.5, text: "Oh yeah", singer:"freddie"},
    { time: 172, text: "Bloody, filthy, in this rap shhh-", singer:"other"},
    { time: 175, text: "You gonna have to kill me, since you can't beat me", singer:"other"},
    { time: 175.5, text: "Oh yeah", singer:"freddie"},
    { time: 176.5, text: "Pras, Dirty, Cash, you're the greedy", singer:"other"},
    { time: 179, text: "Believe me, you gotta let me fly like R. Kelly", singer:"other"},
    { time: 180.5, text: "Oh yeah", singer:"freddie"},
    { time: 181, text: "Bite another dust with my man Freddie Mercury", singer:"other"},
    { time: 183, text: "What height nineties got ya cash, wannabe crazy (Navy Seal)", singer:"other"},
    { time: 185, text: "Oh yeah", singer:"freddie"},

    { time: 185.5, text: "Practically, I tactically destroy", singer:"other"},
    { time: 188.5, text: "Deploy more decoys than a presidential convoy", singer:"other"},
    { time: 189.5, text: "Oh yeah", singer:"freddie"},
    { time: 190.5, text: "My whole envoy stay camouflaged out", singer:"other"},
    { time: 192.5, text: "And when I walk the street, I take the refugee route", singer:"other"},
    { time: 194, text: "Oh yeah", singer:"freddie"},
    { time: 195, text: "This one go out to all my thugs in the borough", singer:"other"},
    { time: 197, text: "Soldiers stay thorough, like Kilamanjaro", singer:"other"},
    { time: 198.5, text: "Oh yeah", singer:"freddie"},
    { time: 199, text: "Split it with an arrow, my girl platoon roll", singer:"other"},
    { time: 201.5, text: "Outta control, the female Mandingos", singer:"other"},
    { time: 203, text: "Oh yeah", singer:"freddie"},
    { time: 204, text: "Free, I evolve from the egg of a seminarian", singer:"other"},
    { time: 206, text: "Don't go down, 'cause I'm a vegetarian", singer:"other"},
    { time: 207, text: "Oh yeah", singer:"freddie"},
    { time: 208.5, text: "And when I bust, it ain't \"in God we trust\"", singer:"other"},
    { time: 210, text: "And if you bring a gun, you better bring a black tusk", singer:"other"},
    { time: 212, text: "Oh yeah", singer:"freddie"},

    { time: 212.5, text: "She looked into my eyes and said FBI", singer:"other"},
    { time: 214.5, text: "Another one bites the dust", singer:"freddie"},
    { time: 216.5, text: "Oh yeah", singer:"freddie"},
    { time: 217, text: "She said she loved me, she was a spy who lied", singer:"other"},
    { time: 220, text: "Another one bites the dust", singer:"freddie"},
    { time: 221, text: "Right", singer:"other"},
    { time: 222.5, text: "I could relate, could you relate?", singer:"other"},
    { time: 224.5, text: "Another one bites the dust", singer:"freddie"},
    { time: 227, text: "Jerry \"Wonda\", The Product", singer:"other"},
    { time: 228.5, text: "Oh-oh", singer:"freddie"},
    { time: 228.5, text: "Another one bites the dust", singer:"freddie"},
    { time: 231, text: "Yo, Canibus, John Forté", singer:"other"},
    { time: 231, text: "Don't you know we coming for you?", singer:"freddie"},
    { time: 234, text: "Another one bites the dust", singer:"freddie"},
    { time: 235, text: "Yo, Dirty Cash, and baby Free", singer:"other"},
    { time: 237.5, text: "Another one bites the dust", singer:"freddie"},
    { time: 240, text: "And another one gone", singer:"freddie"},
    { time: 240, text: "Wyclef Jean", singer:"other"},
    { time: 241, text: "And another one gone", singer:"freddie"},
    { time: 241, text: "Freddie Mercury, ha-ha", singer:"other"},
    { time: 242, text: "Another one bites the dust, yeah", singer:"freddie"},
    { time: 243, text: "I'm out baby", singer:"other"},
    { time: 246, text: "Navy SEALs!", singer:"other"},
    { time: 247, text: "Another one bites the dust", singer:"freddie"},
    { time: 251, text: "Another one bites the dust", singer:"freddie"},
    { time: 255, text: "Another one bites the dust", singer:"freddie"},

];
let currentLyricIndex = 0;
const audio = document.getElementById("audio");
const freddieLyrics = document.getElementById("lyric-freddie");
const othersLyrics = document.getElementById("lyric-others");
   
audio.addEventListener("play", () => {
    setInterval(displayLyrics, 100);
});
   
function displayLyrics() {
    const currentTime = audio.currentTime;
    
    if (
        currentLyricIndex < lyrics.length &&
        currentTime >= lyrics[currentLyricIndex].time
    ) {
        let lyric = lyrics[currentLyricIndex]
        if(lyric.singer === "freddie"){
            freddieLyrics.innerText = lyric.text;
        }else{
            othersLyrics.innerText = lyric.text;
        }
    currentLyricIndex++;
           
    }
}